# Analysis of UK Inflation: Trends in Food, Energy, and Housing Indices

**Importing Libraries & Datasets**
(Filtering Data to Procure Relevant Time Frame)

In [12]:
import pandas as pd

# Load Food at Home CPI
food_df = pd.read_csv(r"D:\Masters Study Abroad\BA 2nd Sem\IS6611 Applied Research in Business Analytics\IS6611 IT Artefact V3\Final Files\Final Datasets\UK Inflation Raw\UK_Food_Index.csv", skiprows=501, header=None)
# Load Energy CPI
energy_df = pd.read_csv(r"D:\Masters Study Abroad\BA 2nd Sem\IS6611 Applied Research in Business Analytics\IS6611 IT Artefact V3\Final Files\Final Datasets\UK Inflation Raw\UK_Energy_Index.csv", skiprows=518, header=None)
# Load Housing CPI
housing_df = pd.read_csv(r"D:\Masters Study Abroad\BA 2nd Sem\IS6611 Applied Research in Business Analytics\IS6611 IT Artefact V3\Final Files\Final Datasets\UK Inflation Raw\UK_Housing_Index.csv", skiprows=501, header=None)

In [13]:
# Display to confirm
display(food_df.head())
display(energy_df.head())
display(housing_df.head())

          0    1
0  2015 JAN  0.3
1  2015 FEB  0.0
2  2015 MAR  0.0
3  2015 APR -0.1
4  2015 MAY  0.1

          0      1
0  2015 JAN  100.5
1  2015 FEB   99.9
2  2015 MAR  100.7
3  2015 APR  101.3
4  2015 MAY  102.0

          0    1
0  2015 JAN  0.5
1  2015 FEB  0.4
2  2015 MAR  0.3
3  2015 APR  0.3
4  2015 MAY  0.4

**Assigning Columns Names**

In [14]:
# Assign column names
food_df.columns = ['Date', 'Food_Index']
energy_df.columns = ['Date', 'Energy_Index']
housing_df.columns = ['Date', 'Housing_Index']

# Display to confirm
display(food_df.head())
display(energy_df.head())
display(housing_df.head())

       Date  Food_Index
0  2015 JAN         0.3
1  2015 FEB         0.0
2  2015 MAR         0.0
3  2015 APR        -0.1
4  2015 MAY         0.1

       Date  Energy_Index
0  2015 JAN         100.5
1  2015 FEB          99.9
2  2015 MAR         100.7
3  2015 APR         101.3
4  2015 MAY         102.0

       Date  Housing_Index
0  2015 JAN            0.5
1  2015 FEB            0.4
2  2015 MAR            0.3
3  2015 APR            0.3
4  2015 MAY            0.4

**Converting the 'Date' column in all three DataFrames**

In [15]:
food_df['Date'] = pd.to_datetime(food_df['Date'], format='%Y %b')
energy_df['Date'] = pd.to_datetime(energy_df['Date'], format='%Y %b')
housing_df['Date'] = pd.to_datetime(housing_df['Date'], format='%Y %b')

# Display to confirm correct datetime conversion
display(food_df.head())
display(energy_df.head())
display(housing_df.head())

        Date  Food_Index
0 2015-01-01         0.3
1 2015-02-01         0.0
2 2015-03-01         0.0
3 2015-04-01        -0.1
4 2015-05-01         0.1

        Date  Energy_Index
0 2015-01-01         100.5
1 2015-02-01          99.9
2 2015-03-01         100.7
3 2015-04-01         101.3
4 2015-05-01         102.0

        Date  Housing_Index
0 2015-01-01            0.5
1 2015-02-01            0.4
2 2015-03-01            0.3
3 2015-04-01            0.3
4 2015-05-01            0.4

**Dataset Consolidation**

In [16]:
# Merge food and energy first
UK_inflation_df = pd.merge(food_df, energy_df, on='Date', how='inner')

# Then merge the result with housing
UK_inflation_df = pd.merge(UK_inflation_df, housing_df, on='Date', how='inner')

# Display the merged DataFrame
display(UK_inflation_df.head())

        Date  Food_Index  Energy_Index  Housing_Index
0 2015-01-01         0.3         100.5            0.5
1 2015-02-01         0.0          99.9            0.4
2 2015-03-01         0.0         100.7            0.3
3 2015-04-01        -0.1         101.3            0.3
4 2015-05-01         0.1         102.0            0.4

**Computing Percentage Growth in Inflation Indices**
(Calculating percentage growth for the Energy index only, since the other indices are already expressed as percentage growth.)

In [17]:
# Get the base (Jan 2015) energy index value
base_energy = UK_inflation_df['Energy_Index'].iloc[0]

# Convert Energy Index to % growth from Jan 2015
UK_inflation_df['Energy_Growth_%'] = ((UK_inflation_df['Energy_Index'] - base_energy) / base_energy * 100).round(2)

# Rename the existing columns Food_Index and Housing_Index
UK_inflation_df.rename(columns={
    'Food_Index': 'Food_Growth_%',
    'Housing_Index': 'Housing_Growth_%'
}, inplace=True)

In [18]:
display(UK_inflation_df.head())

        Date  Food_Growth_%  Energy_Index  Housing_Growth_%  Energy_Growth_%
0 2015-01-01            0.3         100.5               0.5             0.00
1 2015-02-01            0.0          99.9               0.4            -0.60
2 2015-03-01            0.0         100.7               0.3             0.20
3 2015-04-01           -0.1         101.3               0.3             0.80
4 2015-05-01            0.1         102.0               0.4             1.49

**Final Dataset Export**

In [19]:
# Export to CSV
UK_inflation_df.to_csv(r"D:\Masters Study Abroad\BA 2nd Sem\IS6611 Applied Research in Business Analytics\IS6611 IT Artefact V3\Final Files\Final Datasets\UK Inflation Raw\UK_inflation_index.csv", index=False)