# Analyzing and Forecasting NASDAQ Stocks

**Importing Libraries and Dataset**

In [70]:
import pandas as pd

# Load the NASDAQ dataset
file_path = r"D:\Masters Study Abroad\BA 2nd Sem\IS6611 Applied Research in Business Analytics\IS6611 IT Artefact V3\Datasets\US Stocks\NASDAQ Dataset.csv"

# Try loading and displaying basic info
df_stocks = pd.read_csv(file_path)

# Quick overview
print(df_stocks.shape)
print(df_stocks.columns)
df_stocks.head()

(2515, 501)
Index(['Date', 'AAPL_Close/Last', 'AAPL_Volume', 'AAPL_Open', 'AAPL_High',
       'AAPL_Low', 'Abnb_Close/Last', 'Abnb_Volume', 'Abnb_Open', 'Abnb_High',
       ...
       'XEL_Close/Last', 'XEL_Volume', 'XEL_Open', 'XEL_High', 'XEL_Low',
       'ZS_Close/Last', 'ZS_Volume', 'ZS_Open', 'ZS_High', 'ZS_Low'],
      dtype='object', length=501)

C:\Users\shamg\AppData\Local\Temp\ipykernel_18700\2292945097.py:7: DtypeWarning: Columns (66,68,69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df_stocks = pd.read_csv(file_path)

,Date,AAPL_Close/Last,AAPL_Volume,AAPL_Open,AAPL_High,AAPL_Low,Abnb_Close/Last,Abnb_Volume,Abnb_Open,Abnb_High,...,XEL_Close/Last,XEL_Volume,XEL_Open,XEL_High,XEL_Low,ZS_Close/Last,ZS_Volume,ZS_Open,ZS_High,ZS_Low
0,2015-06-30,$31.3562,177304200.0,$31.3925,$31.53,$31.215,NaN,NaN,NaN,NaN,...,$32.18,4141910.0,$32.26,$32.38,$32.02,NaN,NaN,NaN,NaN,NaN
1,2015-07-01,$31.65,120827560.0,$31.725,$31.735,$31.4975,NaN,NaN,NaN,NaN,...,$32.50,3625871.0,$32.23,$32.53,$32.12,NaN,NaN,NaN,NaN,NaN
2,2015-07-02,$31.61,108684720.0,$31.6075,$31.6725,$31.4425,NaN,NaN,NaN,NaN,...,$32.82,2794681.0,$32.83,$33.00,$32.61,NaN,NaN,NaN,NaN,NaN
3,2015-07-06,$31.50,111891800.0,$31.235,$31.5575,$31.2125,NaN,NaN,NaN,NaN,...,$32.94,2641703.0,$32.79,$32.99,$32.64,NaN,NaN,NaN,NaN,NaN
4,2015-07-07,$31.4225,186948360.0,$31.4725,$31.5375,$30.9425,NaN,NaN,NaN,NaN,...,$33.89,3585920.0,$33.13,$33.96,$33.06,NaN,NaN,NaN,NaN,NaN

In [71]:
# Ensure 'Date' is parsed and set as the datetime index
df_stocks['Date'] = pd.to_datetime(df_stocks['Date'], errors='coerce')  # parse and handle any bad dates
df_stocks.dropna(subset=['Date'], inplace=True)                         # drop rows with invalid dates
df_stocks.set_index('Date', inplace=True)
df_stocks.sort_index(inplace=True)  # optional: keep dates in order

In [72]:
# Remove '$' and commas, then convert to numeric
for col in df_stocks.columns:
    if any(col.endswith(suffix) for suffix in ['_Open', '_High', '_Low', '_Close/Last']):
        df_stocks[col] = (
            df_stocks[col]
            .astype(str)
            .str.replace('$', '', regex=False)
            .str.replace(',', '', regex=False)
        )
        df_stocks[col] = pd.to_numeric(df_stocks[col], errors='coerce')

In [73]:
#Verification
df_stocks[['AAPL_Close/Last', 'AAPL_Open']].dtypes  # should show float64 now

AAPL_Close/Last    float64
AAPL_Open          float64
dtype: object

In [74]:
# Print all column names
for i, col in enumerate(df_stocks.columns):
    print(f"{i}: {col}")

0: AAPL_Close/Last
1: AAPL_Volume
2: AAPL_Open
3: AAPL_High
4: AAPL_Low
5: Abnb_Close/Last
6: Abnb_Volume
7: Abnb_Open
8: Abnb_High
9: Abnb_Low
10: adbe_Close/Last
11: adbe_Volume
12: adbe_Open
13: adbe_High
14: adbe_Low
15: adi_Close/Last
16: adi_Volume
17: adi_Open
18: adi_High
19: adi_Low
20: adp_Close/Last
21: adp_Volume
22: adp_Open
23: adp_High
24: adp_Low
25: adsk_Close/Last
26: adsk_Volume
27: adsk_Open
28: adsk_High
29: adsk_Low
30: aep_Close/Last
31: aep_Volume
32: aep_Open
33: aep_High
34: aep_Low
35: amat_Close/Last
36: amat_Volume
37: amat_Open
38: amat_High
39: amat_Low
40: amd_Close/Last
41: amd_Volume
42: amd_Open
43: amd_High
44: amd_Low
45: amgn_Close/Last
46: amgn_Volume
47: amgn_Open
48: amgn_High
49: amgn_Low
50: amzn_Close/Last
51: amzn_Volume
52: amzn_Open
53: amzn_High
54: amzn_Low
55: anss_Close/Last
56: anss_Volume
57: anss_Open
58: anss_High
59: anss_Low
60: app_Close/Last
61: app_Volume
62: app_Open
63: app_High
64: app_Low
65: arm_Close/Last
66: arm_Volume
67: arm_Open
68: arm_High
69: arm_Low
70: asml_Close/Last
71: asml_Volume
72: asml_Open
73: asml_High
74: asml_Low
75: avgo_Close/Last
76: avgo_Volume
77: avgo_Open
78: avgo_High
79: avgo_Low
80: axon_Close/Last
81: axon_Volume
82: axon_Open
83: axon_High
84: axon_Low
85: azn_Close/Last
86: azn_Volume
87: azn_Open
88: azn_High
89: azn_Low
90: biib_Close/Last
91: biib_Volume
92: biib_Open
93: biib_High
94: biib_Low
95: bkng_Close/Last
96: bkng_Volume
97: bkng_Open
98: bkng_High
99: bkng_Low
100: bkr_Close/Last
101: bkr_Volume
102: bkr_Open
103: bkr_High
104: bkr_Low
105: ccep_Close/Last
106: ccep_Volume
107: ccep_Open
108: ccep_High
109: ccep_Low
110: cdns_Close/Last
111: cdns_Volume
112: cdns_Open
113: cdns_High
114: cdns_Low
115: cdw_Close/Last
116: cdw_Volume
117: cdw_Open
118: cdw_High
119: cdw_Low
120: ceg_Close/Last
121: ceg_Volume
122: ceg_Open
123: ceg_High
124: ceg_Low
125: chtr_Close/Last
126: chtr_Volume
127: chtr_Open
128: chtr_High
129: chtr_Low
130: cmcsa_Close/Last
131: cmcsa_Volume
132: cmcsa_Open
133: cmcsa_High
134: cmcsa_Low
135: cost_Close/Last
136: cost_Volume
137: cost_Open
138: cost_High
139: cost_Low
140: cprt_Close/Last
141: cprt_Volume
142: cprt_Open
143: cprt_High
144: cprt_Low
145: crwd_Close/Last
146: crwd_Volume
147: crwd_Open
148: crwd_High
149: crwd_Low
150: csco_Close/Last
151: csco_Volume
152: csco_Open
153: csco_High
154: csco_Low
155: csgp_Close/Last
156: csgp_Volume
157: csgp_Open
158: csgp_High
159: csgp_Low
160: csx_Close/Last
161: csx_Volume
162: csx_Open
163: csx_High
164: csx_Low
165: ctas_Close/Last
166: ctas_Volume
167: ctas_Open
168: ctas_High
169: ctas_Low
170: ctsh_Close/Last
171: ctsh_Volume
172: ctsh_Open
173: ctsh_High
174: ctsh_Low
175: dash_Close/Last
176: dash_Volume
177: dash_Open
178: dash_High
179: dash_Low
180: ddog_Close/Last
181: ddog_Volume
182: ddog_Open
183: ddog_High
184: ddog_Low
185: dxcm_Close/Last
186: dxcm_Volume
187: dxcm_Open
188: dxcm_High
189: dxcm_Low
190: ea_Close/Last
191: ea_Volume
192: ea_Open
193: ea_High
194: ea_Low
195: exc_Close/Last
196: exc_Volume
197: exc_Open
198: exc_High
199: exc_Low
200: fang_Close/Last
201: fang_Volume
202: fang_Open
203: fang_High
204: fang_Low
205: fast_Close/Last
206: fast_Volume
207: fast_Open
208: fast_High
209: fast_Low
210: ftnt_Close/Last
211: ftnt_Volume
212: ftnt_Open
213: ftnt_High
214: ftnt_Low
215: gehc_Close/Last
216: gehc_Volume
217: gehc_Open
218: gehc_High
219: gehc_Low
220: gfs_Close/Last
221: gfs_Volume
222: gfs_Open
223: gfs_High
224: gfs_Low
225: gild_Close/Last
226: gild_Volume
227: gild_Open
228: gild_High
229: gild_Low
230: goog_Close/Last
231: goog_Volume
232: goog_Open
233: goog_High
234: goog_Low
235: googl_Close/Last
236: googl_Volume
237: googl_Open
238: googl_High
239: googl_Low
240: IDXX_Close/Last
241: IDXX_Volume
242: IDXX_Open
243: IDXX_High
244: IDXX_Low
245: INTC_Close/Last
246: INTC_Volume
247: INTC_Open
248: INTC_High
249: INTC_Low
250: INTU_Close/Last
251: INTU_Volume
252: INTU_Open
253: INTU_High
254: INTU_Low
255: isrg_Close/Last
256: isrg_Volume
257: isrg_Open
258: isrg_High
259: isrg_Low
260: KDP_Close/Last
261: KDP_Volume
262: KDP_Open
263: KDP_High
264: KDP_Low
265: KHC_Close/Last
266: KHC_Volume
267: KHC_Open
268: KHC_High
269: KHC_Low
270: KLAC_Close/Last
271: KLAC_Volume
272: KLAC_Open
273: KLAC_High
274: KLAC_Low
275: LIN_Close/Last
276: LIN_Volume
277: LIN_Open
278: LIN_High
279: LIN_Low
280: LRCX_Close/Last
281: LRCX_Volume
282: LRCX_Open
283: LRCX_High
284: LRCX_Low
285: LULU_Close/Last
286: LULU_Volume
287: LULU_Open
288: LULU_High
289: LULU_Low
290: MAR_Close/Last
291: MAR_Volume
292: MAR_Open
293: MAR_High
294: MAR_Low
295: MCHP_Close/Last
296: MCHP_Volume
297: MCHP_Open
298: MCHP_High
299: MCHP_Low
300: MDLZ_Close/Last
301: MDLZ_Volume
302: MDLZ_Open
303: MDLZ_High
304: MDLZ_Low
305: MELI_Close/Last
306: MELI_Volume
307: MELI_Open
308: MELI_High
309: MELI_Low
310: META_Close/Last
311: META_Volume
312: META_Open
313: META_High
314: META_Low
315: MNST_Close/Last
316: MNST_Volume
317: MNST_Open
318: MNST_High
319: MNST_Low
320: MRVL_Close/Last
321: MRVL_Volume
322: MRVL_Open
323: MRVL_High
324: MRVL_Low
325: MSFT_Close/Last
326: MSFT_Volume
327: MSFT_Open
328: MSFT_High
329: MSFT_Low
330: MSTR_Close/Last
331: MSTR_Volume
332: MSTR_Open
333: MSTR_High
334: MSTR_Low
335: MU_Close/Last
336: MU_Volume
337: MU_Open
338: MU_High
339: MU_Low
340: NFLX_Close/Last
341: NFLX_Volume
342: NFLX_Open
343: NFLX_High
344: NFLX_Low
345: NVDA_Close/Last
346: NVDA_Volume
347: NVDA_Open
348: NVDA_High
349: NVDA_Low
350: NXPI_Close/Last
351: NXPI_Volume
352: NXPI_Open
353: NXPI_High
354: NXPI_Low
355: ODLF_Close/Last
356: ODLF_Volume
357: ODLF_Open
358: ODLF_High
359: ODLF_Low
360: ON_Close/Last
361: ON_Volume
362: ON_Open
363: ON_High
364: ON_Low
365: ORLY_Close/Last
366: ORLY_Volume
367: ORLY_Open
368: ORLY_High
369: ORLY_Low
370: PANW_Close/Last
371: PANW_Volume
372: PANW_Open
373: PANW_High
374: PANW_Low
375: PAYX_Close/Last
376: PAYX_Volume
377: PAYX_Open
378: PAYX_High
379: PAYX_Low
380: PCAR_Close/Last
381: PCAR_Volume
382: PCAR_Open
383: PCAR_High
384: PCAR_Low
385: PDD_Close/Last
386: PDD_Volume
387: PDD_Open
388: PDD_High
389: PDD_Low
390: PEP_Close/Last
391: PEP_Volume
392: PEP_Open
393: PEP_High
394: PEP_Low
395: PLTR_Close/Last
396: PLTR_Volume
397: PLTR_Open
398: PLTR_High
399: PLTR_Low
400: PYPL_Close/Last
401: PYPL_Volume
402: PYPL_Open
403: PYPL_High
404: PYPL_Low
405: QCOM_Close/Last
406: QCOM_Volume
407: QCOM_Open
408: QCOM_High
409: QCOM_Low
410: REGN_Close/Last
411: REGN_Volume
412: REGN_Open
413: REGN_High
414: REGN_Low
415: ROP_Close/Last
416: ROP_Volume
417: ROP_Open
418: ROP_High
419: ROP_Low
420: ROST_Close/Last
421: ROST_Volume
422: ROST_Open
423: ROST_High
424: ROST_Low
425: SBUX_Close/Last
426: SBUX_Volume
427: SBUX_Open
428: SBUX_High
429: SBUX_Low
430: SHOP_Close/Last
431: SHOP_Volume
432: SHOP_Open
433: SHOP_High
434: SHOP_Low
435: SNPS_Close/Last
436: SNPS_Volume
437: SNPS_Open
438: SNPS_High
439: SNPS_Low
440: TEAM_Close/Last
441: TEAM_Volume
442: TEAM_Open
443: TEAM_High
444: TEAM_Low
445: TMUS_Close/Last
446: TMUS_Volume
447: TMUS_Open
448: TMUS_High
449: TMUS_Low
450: TSLA_Close/Last
451: TSLA_Volume
452: TSLA_Open
453: TSLA_High
454: TSLA_Low
455: TTD_Close/Last
456: TTD_Volume
457: TTD_Open
458: TTD_High
459: TTD_Low
460: TTWO_Close/Last
461: TTWO_Volume
462: TTWO_Open
463: TTWO_High
464: TTWO_Low
465: TXN_Close/Last
466: TXN_Volume
467: TXN_Open
468: TXN_High
469: TXN_Low
470: VRSK_Close/Last
471: VRSK_Volume
472: VRSK_Open
473: VRSK_High
474: VRSK_Low
475: VRTX_Close/Last
476: VRTX_Volume
477: VRTX_Open
478: VRTX_High
479: VRTX_Low
480: WBD_Close/Last
481: WBD_Volume
482: WBD_Open
483: WBD_High
484: WBD_Low
485: WDAY_Close/Last
486: WDAY_Volume
487: WDAY_Open
488: WDAY_High
489: WDAY_Low
490: XEL_Close/Last
491: XEL_Volume
492: XEL_Open
493: XEL_High
494: XEL_Low
495: ZS_Close/Last
496: ZS_Volume
497: ZS_Open
498: ZS_High
499: ZS_Low

In [75]:
# Drop all columns containing '_Volume' in their name
df_stocks = df_stocks.loc[:, ~df_stocks.columns.str.contains('_Volume')]

In [76]:
# Print all column names
for i, col in enumerate(df_stocks.columns):
    print(f"{i}: {col}")

0: AAPL_Close/Last
1: AAPL_Open
2: AAPL_High
3: AAPL_Low
4: Abnb_Close/Last
5: Abnb_Open
6: Abnb_High
7: Abnb_Low
8: adbe_Close/Last
9: adbe_Open
10: adbe_High
11: adbe_Low
12: adi_Close/Last
13: adi_Open
14: adi_High
15: adi_Low
16: adp_Close/Last
17: adp_Open
18: adp_High
19: adp_Low
20: adsk_Close/Last
21: adsk_Open
22: adsk_High
23: adsk_Low
24: aep_Close/Last
25: aep_Open
26: aep_High
27: aep_Low
28: amat_Close/Last
29: amat_Open
30: amat_High
31: amat_Low
32: amd_Close/Last
33: amd_Open
34: amd_High
35: amd_Low
36: amgn_Close/Last
37: amgn_Open
38: amgn_High
39: amgn_Low
40: amzn_Close/Last
41: amzn_Open
42: amzn_High
43: amzn_Low
44: anss_Close/Last
45: anss_Open
46: anss_High
47: anss_Low
48: app_Close/Last
49: app_Open
50: app_High
51: app_Low
52: arm_Close/Last
53: arm_Open
54: arm_High
55: arm_Low
56: asml_Close/Last
57: asml_Open
58: asml_High
59: asml_Low
60: avgo_Close/Last
61: avgo_Open
62: avgo_High
63: avgo_Low
64: axon_Close/Last
65: axon_Open
66: axon_High
67: axon_Low
68: azn_Close/Last
69: azn_Open
70: azn_High
71: azn_Low
72: biib_Close/Last
73: biib_Open
74: biib_High
75: biib_Low
76: bkng_Close/Last
77: bkng_Open
78: bkng_High
79: bkng_Low
80: bkr_Close/Last
81: bkr_Open
82: bkr_High
83: bkr_Low
84: ccep_Close/Last
85: ccep_Open
86: ccep_High
87: ccep_Low
88: cdns_Close/Last
89: cdns_Open
90: cdns_High
91: cdns_Low
92: cdw_Close/Last
93: cdw_Open
94: cdw_High
95: cdw_Low
96: ceg_Close/Last
97: ceg_Open
98: ceg_High
99: ceg_Low
100: chtr_Close/Last
101: chtr_Open
102: chtr_High
103: chtr_Low
104: cmcsa_Close/Last
105: cmcsa_Open
106: cmcsa_High
107: cmcsa_Low
108: cost_Close/Last
109: cost_Open
110: cost_High
111: cost_Low
112: cprt_Close/Last
113: cprt_Open
114: cprt_High
115: cprt_Low
116: crwd_Close/Last
117: crwd_Open
118: crwd_High
119: crwd_Low
120: csco_Close/Last
121: csco_Open
122: csco_High
123: csco_Low
124: csgp_Close/Last
125: csgp_Open
126: csgp_High
127: csgp_Low
128: csx_Close/Last
129: csx_Open
130: csx_High
131: csx_Low
132: ctas_Close/Last
133: ctas_Open
134: ctas_High
135: ctas_Low
136: ctsh_Close/Last
137: ctsh_Open
138: ctsh_High
139: ctsh_Low
140: dash_Close/Last
141: dash_Open
142: dash_High
143: dash_Low
144: ddog_Close/Last
145: ddog_Open
146: ddog_High
147: ddog_Low
148: dxcm_Close/Last
149: dxcm_Open
150: dxcm_High
151: dxcm_Low
152: ea_Close/Last
153: ea_Open
154: ea_High
155: ea_Low
156: exc_Close/Last
157: exc_Open
158: exc_High
159: exc_Low
160: fang_Close/Last
161: fang_Open
162: fang_High
163: fang_Low
164: fast_Close/Last
165: fast_Open
166: fast_High
167: fast_Low
168: ftnt_Close/Last
169: ftnt_Open
170: ftnt_High
171: ftnt_Low
172: gehc_Close/Last
173: gehc_Open
174: gehc_High
175: gehc_Low
176: gfs_Close/Last
177: gfs_Open
178: gfs_High
179: gfs_Low
180: gild_Close/Last
181: gild_Open
182: gild_High
183: gild_Low
184: goog_Close/Last
185: goog_Open
186: goog_High
187: goog_Low
188: googl_Close/Last
189: googl_Open
190: googl_High
191: googl_Low
192: IDXX_Close/Last
193: IDXX_Open
194: IDXX_High
195: IDXX_Low
196: INTC_Close/Last
197: INTC_Open
198: INTC_High
199: INTC_Low
200: INTU_Close/Last
201: INTU_Open
202: INTU_High
203: INTU_Low
204: isrg_Close/Last
205: isrg_Open
206: isrg_High
207: isrg_Low
208: KDP_Close/Last
209: KDP_Open
210: KDP_High
211: KDP_Low
212: KHC_Close/Last
213: KHC_Open
214: KHC_High
215: KHC_Low
216: KLAC_Close/Last
217: KLAC_Open
218: KLAC_High
219: KLAC_Low
220: LIN_Close/Last
221: LIN_Open
222: LIN_High
223: LIN_Low
224: LRCX_Close/Last
225: LRCX_Open
226: LRCX_High
227: LRCX_Low
228: LULU_Close/Last
229: LULU_Open
230: LULU_High
231: LULU_Low
232: MAR_Close/Last
233: MAR_Open
234: MAR_High
235: MAR_Low
236: MCHP_Close/Last
237: MCHP_Open
238: MCHP_High
239: MCHP_Low
240: MDLZ_Close/Last
241: MDLZ_Open
242: MDLZ_High
243: MDLZ_Low
244: MELI_Close/Last
245: MELI_Open
246: MELI_High
247: MELI_Low
248: META_Close/Last
249: META_Open
250: META_High
251: META_Low
252: MNST_Close/Last
253: MNST_Open
254: MNST_High
255: MNST_Low
256: MRVL_Close/Last
257: MRVL_Open
258: MRVL_High
259: MRVL_Low
260: MSFT_Close/Last
261: MSFT_Open
262: MSFT_High
263: MSFT_Low
264: MSTR_Close/Last
265: MSTR_Open
266: MSTR_High
267: MSTR_Low
268: MU_Close/Last
269: MU_Open
270: MU_High
271: MU_Low
272: NFLX_Close/Last
273: NFLX_Open
274: NFLX_High
275: NFLX_Low
276: NVDA_Close/Last
277: NVDA_Open
278: NVDA_High
279: NVDA_Low
280: NXPI_Close/Last
281: NXPI_Open
282: NXPI_High
283: NXPI_Low
284: ODLF_Close/Last
285: ODLF_Open
286: ODLF_High
287: ODLF_Low
288: ON_Close/Last
289: ON_Open
290: ON_High
291: ON_Low
292: ORLY_Close/Last
293: ORLY_Open
294: ORLY_High
295: ORLY_Low
296: PANW_Close/Last
297: PANW_Open
298: PANW_High
299: PANW_Low
300: PAYX_Close/Last
301: PAYX_Open
302: PAYX_High
303: PAYX_Low
304: PCAR_Close/Last
305: PCAR_Open
306: PCAR_High
307: PCAR_Low
308: PDD_Close/Last
309: PDD_Open
310: PDD_High
311: PDD_Low
312: PEP_Close/Last
313: PEP_Open
314: PEP_High
315: PEP_Low
316: PLTR_Close/Last
317: PLTR_Open
318: PLTR_High
319: PLTR_Low
320: PYPL_Close/Last
321: PYPL_Open
322: PYPL_High
323: PYPL_Low
324: QCOM_Close/Last
325: QCOM_Open
326: QCOM_High
327: QCOM_Low
328: REGN_Close/Last
329: REGN_Open
330: REGN_High
331: REGN_Low
332: ROP_Close/Last
333: ROP_Open
334: ROP_High
335: ROP_Low
336: ROST_Close/Last
337: ROST_Open
338: ROST_High
339: ROST_Low
340: SBUX_Close/Last
341: SBUX_Open
342: SBUX_High
343: SBUX_Low
344: SHOP_Close/Last
345: SHOP_Open
346: SHOP_High
347: SHOP_Low
348: SNPS_Close/Last
349: SNPS_Open
350: SNPS_High
351: SNPS_Low
352: TEAM_Close/Last
353: TEAM_Open
354: TEAM_High
355: TEAM_Low
356: TMUS_Close/Last
357: TMUS_Open
358: TMUS_High
359: TMUS_Low
360: TSLA_Close/Last
361: TSLA_Open
362: TSLA_High
363: TSLA_Low
364: TTD_Close/Last
365: TTD_Open
366: TTD_High
367: TTD_Low
368: TTWO_Close/Last
369: TTWO_Open
370: TTWO_High
371: TTWO_Low
372: TXN_Close/Last
373: TXN_Open
374: TXN_High
375: TXN_Low
376: VRSK_Close/Last
377: VRSK_Open
378: VRSK_High
379: VRSK_Low
380: VRTX_Close/Last
381: VRTX_Open
382: VRTX_High
383: VRTX_Low
384: WBD_Close/Last
385: WBD_Open
386: WBD_High
387: WBD_Low
388: WDAY_Close/Last
389: WDAY_Open
390: WDAY_High
391: WDAY_Low
392: XEL_Close/Last
393: XEL_Open
394: XEL_High
395: XEL_Low
396: ZS_Close/Last
397: ZS_Open
398: ZS_High
399: ZS_Low

In [77]:
# Rename all columns ending with '_Close/Last' to '_Close'
df_stocks.rename(columns=lambda col: col.replace('_Close/Last', '_Close') if col.endswith('_Close/Last') else col, inplace=True)

In [78]:
# Print all column names
for i, col in enumerate(df_stocks.columns):
    print(f"{i}: {col}")

0: AAPL_Close
1: AAPL_Open
2: AAPL_High
3: AAPL_Low
4: Abnb_Close
5: Abnb_Open
6: Abnb_High
7: Abnb_Low
8: adbe_Close
9: adbe_Open
10: adbe_High
11: adbe_Low
12: adi_Close
13: adi_Open
14: adi_High
15: adi_Low
16: adp_Close
17: adp_Open
18: adp_High
19: adp_Low
20: adsk_Close
21: adsk_Open
22: adsk_High
23: adsk_Low
24: aep_Close
25: aep_Open
26: aep_High
27: aep_Low
28: amat_Close
29: amat_Open
30: amat_High
31: amat_Low
32: amd_Close
33: amd_Open
34: amd_High
35: amd_Low
36: amgn_Close
37: amgn_Open
38: amgn_High
39: amgn_Low
40: amzn_Close
41: amzn_Open
42: amzn_High
43: amzn_Low
44: anss_Close
45: anss_Open
46: anss_High
47: anss_Low
48: app_Close
49: app_Open
50: app_High
51: app_Low
52: arm_Close
53: arm_Open
54: arm_High
55: arm_Low
56: asml_Close
57: asml_Open
58: asml_High
59: asml_Low
60: avgo_Close
61: avgo_Open
62: avgo_High
63: avgo_Low
64: axon_Close
65: axon_Open
66: axon_High
67: axon_Low
68: azn_Close
69: azn_Open
70: azn_High
71: azn_Low
72: biib_Close
73: biib_Open
74: biib_High
75: biib_Low
76: bkng_Close
77: bkng_Open
78: bkng_High
79: bkng_Low
80: bkr_Close
81: bkr_Open
82: bkr_High
83: bkr_Low
84: ccep_Close
85: ccep_Open
86: ccep_High
87: ccep_Low
88: cdns_Close
89: cdns_Open
90: cdns_High
91: cdns_Low
92: cdw_Close
93: cdw_Open
94: cdw_High
95: cdw_Low
96: ceg_Close
97: ceg_Open
98: ceg_High
99: ceg_Low
100: chtr_Close
101: chtr_Open
102: chtr_High
103: chtr_Low
104: cmcsa_Close
105: cmcsa_Open
106: cmcsa_High
107: cmcsa_Low
108: cost_Close
109: cost_Open
110: cost_High
111: cost_Low
112: cprt_Close
113: cprt_Open
114: cprt_High
115: cprt_Low
116: crwd_Close
117: crwd_Open
118: crwd_High
119: crwd_Low
120: csco_Close
121: csco_Open
122: csco_High
123: csco_Low
124: csgp_Close
125: csgp_Open
126: csgp_High
127: csgp_Low
128: csx_Close
129: csx_Open
130: csx_High
131: csx_Low
132: ctas_Close
133: ctas_Open
134: ctas_High
135: ctas_Low
136: ctsh_Close
137: ctsh_Open
138: ctsh_High
139: ctsh_Low
140: dash_Close
141: dash_Open
142: dash_High
143: dash_Low
144: ddog_Close
145: ddog_Open
146: ddog_High
147: ddog_Low
148: dxcm_Close
149: dxcm_Open
150: dxcm_High
151: dxcm_Low
152: ea_Close
153: ea_Open
154: ea_High
155: ea_Low
156: exc_Close
157: exc_Open
158: exc_High
159: exc_Low
160: fang_Close
161: fang_Open
162: fang_High
163: fang_Low
164: fast_Close
165: fast_Open
166: fast_High
167: fast_Low
168: ftnt_Close
169: ftnt_Open
170: ftnt_High
171: ftnt_Low
172: gehc_Close
173: gehc_Open
174: gehc_High
175: gehc_Low
176: gfs_Close
177: gfs_Open
178: gfs_High
179: gfs_Low
180: gild_Close
181: gild_Open
182: gild_High
183: gild_Low
184: goog_Close
185: goog_Open
186: goog_High
187: goog_Low
188: googl_Close
189: googl_Open
190: googl_High
191: googl_Low
192: IDXX_Close
193: IDXX_Open
194: IDXX_High
195: IDXX_Low
196: INTC_Close
197: INTC_Open
198: INTC_High
199: INTC_Low
200: INTU_Close
201: INTU_Open
202: INTU_High
203: INTU_Low
204: isrg_Close
205: isrg_Open
206: isrg_High
207: isrg_Low
208: KDP_Close
209: KDP_Open
210: KDP_High
211: KDP_Low
212: KHC_Close
213: KHC_Open
214: KHC_High
215: KHC_Low
216: KLAC_Close
217: KLAC_Open
218: KLAC_High
219: KLAC_Low
220: LIN_Close
221: LIN_Open
222: LIN_High
223: LIN_Low
224: LRCX_Close
225: LRCX_Open
226: LRCX_High
227: LRCX_Low
228: LULU_Close
229: LULU_Open
230: LULU_High
231: LULU_Low
232: MAR_Close
233: MAR_Open
234: MAR_High
235: MAR_Low
236: MCHP_Close
237: MCHP_Open
238: MCHP_High
239: MCHP_Low
240: MDLZ_Close
241: MDLZ_Open
242: MDLZ_High
243: MDLZ_Low
244: MELI_Close
245: MELI_Open
246: MELI_High
247: MELI_Low
248: META_Close
249: META_Open
250: META_High
251: META_Low
252: MNST_Close
253: MNST_Open
254: MNST_High
255: MNST_Low
256: MRVL_Close
257: MRVL_Open
258: MRVL_High
259: MRVL_Low
260: MSFT_Close
261: MSFT_Open
262: MSFT_High
263: MSFT_Low
264: MSTR_Close
265: MSTR_Open
266: MSTR_High
267: MSTR_Low
268: MU_Close
269: MU_Open
270: MU_High
271: MU_Low
272: NFLX_Close
273: NFLX_Open
274: NFLX_High
275: NFLX_Low
276: NVDA_Close
277: NVDA_Open
278: NVDA_High
279: NVDA_Low
280: NXPI_Close
281: NXPI_Open
282: NXPI_High
283: NXPI_Low
284: ODLF_Close
285: ODLF_Open
286: ODLF_High
287: ODLF_Low
288: ON_Close
289: ON_Open
290: ON_High
291: ON_Low
292: ORLY_Close
293: ORLY_Open
294: ORLY_High
295: ORLY_Low
296: PANW_Close
297: PANW_Open
298: PANW_High
299: PANW_Low
300: PAYX_Close
301: PAYX_Open
302: PAYX_High
303: PAYX_Low
304: PCAR_Close
305: PCAR_Open
306: PCAR_High
307: PCAR_Low
308: PDD_Close
309: PDD_Open
310: PDD_High
311: PDD_Low
312: PEP_Close
313: PEP_Open
314: PEP_High
315: PEP_Low
316: PLTR_Close
317: PLTR_Open
318: PLTR_High
319: PLTR_Low
320: PYPL_Close
321: PYPL_Open
322: PYPL_High
323: PYPL_Low
324: QCOM_Close
325: QCOM_Open
326: QCOM_High
327: QCOM_Low
328: REGN_Close
329: REGN_Open
330: REGN_High
331: REGN_Low
332: ROP_Close
333: ROP_Open
334: ROP_High
335: ROP_Low
336: ROST_Close
337: ROST_Open
338: ROST_High
339: ROST_Low
340: SBUX_Close
341: SBUX_Open
342: SBUX_High
343: SBUX_Low
344: SHOP_Close
345: SHOP_Open
346: SHOP_High
347: SHOP_Low
348: SNPS_Close
349: SNPS_Open
350: SNPS_High
351: SNPS_Low
352: TEAM_Close
353: TEAM_Open
354: TEAM_High
355: TEAM_Low
356: TMUS_Close
357: TMUS_Open
358: TMUS_High
359: TMUS_Low
360: TSLA_Close
361: TSLA_Open
362: TSLA_High
363: TSLA_Low
364: TTD_Close
365: TTD_Open
366: TTD_High
367: TTD_Low
368: TTWO_Close
369: TTWO_Open
370: TTWO_High
371: TTWO_Low
372: TXN_Close
373: TXN_Open
374: TXN_High
375: TXN_Low
376: VRSK_Close
377: VRSK_Open
378: VRSK_High
379: VRSK_Low
380: VRTX_Close
381: VRTX_Open
382: VRTX_High
383: VRTX_Low
384: WBD_Close
385: WBD_Open
386: WBD_High
387: WBD_Low
388: WDAY_Close
389: WDAY_Open
390: WDAY_High
391: WDAY_Low
392: XEL_Close
393: XEL_Open
394: XEL_High
395: XEL_Low
396: ZS_Close
397: ZS_Open
398: ZS_High
399: ZS_Low

In [79]:
# Extracting all stock prefixes based on columns ending with '_Close'
close_columns = [col for col in df_stocks.columns if col.endswith('_Close')]
stock_prefixes = [col.replace('_Close', '') for col in close_columns]

# Confirm sample
print(f"Found {len(stock_prefixes)} stocks.")
print(stock_prefixes[:5])

Found 100 stocks.
['AAPL', 'Abnb', 'adbe', 'adi', 'adp']

In [80]:
from statsmodels.tsa.api import VAR
import pandas as pd
import numpy as np

# Container to store results
forecast_all_df = []
forecast_days = 30
forecast_dates = pd.date_range(start=df_stocks.index[-1] + pd.Timedelta(days=1), periods=forecast_days, freq='B')

for stock in stock_prefixes:
    try:
        # Use only _Open and _Close
        cols = [f"{stock}_Open", f"{stock}_Close"]
        stock_df = df_stocks[cols].dropna()

        if stock_df.shape[0] < 40:
            continue

        # Difference the data
        stock_diff = stock_df.diff().dropna()

        # Fit VAR model
        model = VAR(stock_diff)
        results = model.fit(maxlags=15, ic='aic')

        # Forecast differenced values
        lag_order = results.k_ar
        forecast_input = stock_diff.values[-lag_order:]
        forecast_diff = results.forecast(y=forecast_input, steps=forecast_days)

        # Create DataFrame for forecasted diffs
        forecast_diff_df = pd.DataFrame(forecast_diff, columns=cols)

        # Reconstruct actual values
        last_known = stock_df.iloc[-1]
        forecast_actual = forecast_diff_df.cumsum() + last_known

        # Store only the Close forecast
        forecast_stock = pd.DataFrame({
            'Date': forecast_dates,
            'Forecasted_Close': forecast_actual[f"{stock}_Close"],
            'Stock': stock
        })

        forecast_all_df.append(forecast_stock)

    except Exception as e:
        print(f"❌ Skipped {stock}: {e}")
        continue

# Combine all into one DataFrame
forecast_all_df = pd.concat(forecast_all_df).reset_index(drop=True)

In [81]:
# STEP: Pivot forecast data so each stock becomes a column
pivot_forecast_df = forecast_all_df.pivot(index='Date', columns='Stock', values='Forecasted_Close')

# Reset index so Date is a column
pivot_forecast_df.reset_index(inplace=True)

# Export to CSV for Tableau
pivot_forecast_df.to_csv(r"D:\Masters Study Abroad\BA 2nd Sem\IS6611 Applied Research in Business Analytics\IS6611 IT Artefact V3\Datasets\US Stocks\NASDAQ Dataset_Draft1.csv", index=False)

# Optional: Preview first few rows
pivot_forecast_df.head()

Stock,Date,AAPL,Abnb,IDXX,INTC,INTU,KDP,KHC,KLAC,LIN,...,exc,fang,fast,ftnt,gehc,gfs,gild,goog,googl,isrg
0,2025-07-01,201.725042,134.694125,531.346182,22.662992,776.632208,32.897073,25.608158,889.069372,464.358445,...,42.914275,139.852832,41.926420,103.111945,74.325441,38.437514,110.630788,177.698573,177.838338,544.454820
1,2025-07-02,201.379736,134.366222,531.017939,22.633634,777.467860,32.875164,25.615605,884.410136,464.199462,...,42.908943,139.502216,42.005102,103.099169,73.959142,38.356713,110.726875,177.475433,177.497069,545.292279
2,2025-07-03,201.572074,134.624802,532.008701,22.670263,775.895686,32.914834,25.606393,886.572674,464.062315,...,42.868017,139.824991,41.980594,102.967381,73.923024,38.353073,110.825947,176.962153,176.889319,544.432516
3,2025-07-04,201.533979,134.281548,531.903350,22.842561,777.068493,32.909176,25.589359,886.784931,465.125995,...,42.905483,139.061611,41.940985,103.101850,74.042198,38.528326,110.875762,176.556979,176.396150,543.735896
4,2025-07-07,201.736612,134.599332,532.212107,22.574998,776.414042,32.949955,25.555591,884.438871,465.480343,...,43.000689,139.478160,41.936735,103.114458,74.339432,38.578429,110.340444,176.423679,176.359990,546.046705